version: '3.8'

services:
  # golang
  app:
    build: # ビルドに使うDockerファイルのパス
      context: app
      dockerfile: ./Dockerfile
    volumes: # マウント
      - ./app:/usr/local/go/src/distribu/app
      - .env:/usr/local/go/src/distribu/app/.env
    tty: true # コンテナの永続化

    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: db
    depends_on:
      - db
    ports:
      - 3080:3000
  # posttgresql
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      TZ: "Asia/Tokyo"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  db-store: